### Get user token.
POST http://127.0.0.1:8000/api-token-auth/
Content-Type: application/json

{
  "username": "user",
  "password": "user12345-"
}

### Send POST request to create thread
POST http://127.0.0.1:8000/application/thread/
Content-Type: application/json

{
  "participants": {
    "second_user": 3,
    "first_user": 2
  }
}

### Send DELETE request to create thread
DELETE http://127.0.0.1:8000/application/thread/8/
Content-Type: application/json

### Send GET request to get thread list
GET http://127.0.0.1:8000/application/thread/list
Content-Type: application/json


### Send GET request to get message list for the thread
GET http://127.0.0.1:8000/application/message/
Content-Type: application/json

{
  "thread": 2
}

### Send POST request to create message for the thread
POST http://127.0.0.1:8000/application/message/
Content-Type: application/json

{
  "text": "Me text",
  "thread": 2
}

### Send PUT request to set for the message status
PUT http://127.0.0.1:8000/application/message/4/status/
Content-Type: application/json

{
  "is_read": "true",
  "thread": 2
}